trigger:
- master

variables:
 vmImage: 'ubuntu-latest'
 mavenfilepath: 'apps/pom.xml'

stages:
  - stage: Build
    displayName: Build Stage 
    jobs:
      - job: MavenPackageandPublish
        displayName: Maven Package and Publish Artifacts
        pool:
          vmImage: $(vmImage)
        steps:
        - task: Maven@4
          inputs:
            mavenPomFile: $(mavenfilepath)
            publishJUnitResults: false
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)'
            Contents: '**/*.jar'
            TargetFolder: '$(Pipeline.Workspace)'
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(Pipeline.Workspace)'
            artifact: 'drop'
            publishLocation: 'pipeline'