trigger:
- master

variables:
 vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: Build Stage 
    jobs:
      - job: MavenPackageandPublish
        displayName: Maven Package and Publish Artifacts
        pool:
          vmImage: $(vmImage)
        steps:
        - task: Maven@4
          inputs:
            mavenPomFile: 'app/pom.xml'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)'
            Contents: '''**/target/*.?(war|jar)'''
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(Build.ArtifactStagingDirectory)'
            artifact: 'drop'
            publishLocation: 'pipeline'
            